### ISSUE TITLE
fdr-control fails with out of bounds error

### ISSUE THREAD

**Issue by FelixMoelder** [varlociraptor/varlociraptor#101]
Varlociraptor fdr-control fails for certain kinds of records returning the following error:
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/slice/mod.rs:2717:10`

This error is thrown when processing the following record:
```
17      40293848        DEL00005659     A       <DEL>   .       .       SVLEN=-127;PROB_ARTIFACT=79.1942;PROB_ABSENT=307.83;PROB_PRESENT=0.173908;PROB_FFPE_ARTIFACT=14.0613;ANN=<DEL>|downstream_gene_variant|MODIFIER|CDC6|ENSG00000094804|transcript|ENST00000473555.1|protein_coding||c.*2614delA|||||2614|WARNING_TRANSCRIPT_INCOMPLETE,<DEL>|downstream_gene_variant|MODIFIER|CDC6|ENSG00000094804|transcript|ENST00000580824.5|protein_coding||c.*2293delA|||||2293|WARNING_TRANSCRIPT_INCOMPLETE,<DEL>|downstream_gene_variant|MODIFIER|CDC6|ENSG00000094804|transcript|ENST00000577249.1|protein_coding||c.*2667delA|||||2667|WARNING_TRANSCRIPT_INCOMPLETE,<DEL>|intron_variant|MODIFIER|CDC6|ENSG00000094804|transcript|ENST00000209728.8|protein_coding|5/11|c.837-100delA||||||INFO_REALIGN_3_PRIME,<DEL>|intron_variant|MODIFIER|CDC6|ENSG00000094804|transcript|ENST00000582402.1|retained_intron|1/1|n.203-1506delA||||||INFO_REALIGN_3_PRIME   DP:AF:OBS:SB    68:0.0865052:53N*6V*4N-3V-1V+1N+:.
```

Following the backtrace shows that the issue occurs during accessing [svlens](https://github.com/varlociraptor/varlociraptor/blob/ecbe1ad679944183fea924c7670608995993ceeb/src/utils.rs#L218), being empty at this point.

The following [issue](https://github.com/samtools/bcftools/issues/874) suggests that the value -127 is a special value which might cause the panic here.

**Comment by johanneskoester** [comment]
Good catch!

**Comment by bwubb** [comment]
Hello. I am receiving a similar error from preprocess. I am not certain how to do the backtrace nor which variant is causing this error. It is only appearing in a single sample and the input is from Manta results.

```
...
[mem: 1675360 kB, swap: 418304 kB] 4088.23s 121330 records (29.68 records/s)
[mem: 1102428 kB, swap: 418304 kB] 4108.29s 121528 records (29.58 records/s)
[mem: 935900 kB, swap: 418304 kB] 4128.39s 121726 records (29.49 records/s)
thread 'main' panicked at 'index out of bounds: the len is 186739 but the index is 186739', src/variants/types/replacement.rs:253:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by johanneskoester** [comment]
Fixed with latest htslib dependency. @bwubb for your case, we have a separate issue opened.
