### ISSUE TITLE
Missing EVENT tag preprocessing delly calls

### ISSUE THREAD

**Issue by FelixMoelder** [varlociraptor/varlociraptor#113]
It seems like varlociraptor v2.0 has issues preprocessing some bcf files created by delly failing with the following error message: `Error: tag EVENT undefined in BCF/VCF header`.

While this issue does not occur for files created by freebayes, some (not all) delly input bcfs can not be processed.

**Comment by FelixMoelder** [comment]
Investigating the log files of the workflow showed another problem with delly files.
In that case varlociraptor crashes with panic returning `thread 'main' panicked at 'Pattern too long',`

**Comment by johanneskoester** [comment]
Yes, both are solved in the master branch. I am working on one other issue with 2.0 now, before creating a new release.
