### ISSUE TITLE
Bioconda recipe fail

### ISSUE THREAD

**Issue by andersgs** [varlociraptor/varlociraptor#134]
Looks like the latest update failed MacOSX checks: bioconda/bioconda-recipes#25462

Seems to be `hts-sys` failing to compile, missing a reference to `R_OK` --- seems similar to the issue https://github.com/samtools/htslib/commit/0ec5202de5691b27917ce828a9d24c9c729a9b81

according to that issue, `#include <unistd.h>` is not being imported.

**Comment by mbargull** [comment]
Yep, it's a known issue, we're on it -- just had a weekend in between ;).
@johanneskoester just put out some new rust-htslib/hts-sys versions and the varolciraptor one is soon to follow, I assume.

**Comment by dlaehnemann** [comment]
This should be resolved over at bioconda, so I'm closing this. The above mentioned versions and newer version (for example [3.0.1](https://github.com/bioconda/bioconda-recipes/pull/25462)) pass for MacOSX, as well.
