### ISSUE TITLE
GT/PL field

### ISSUE THREAD

**Issue by fbemm** [varlociraptor/varlociraptor#136]
Probably a naive question, is there a way to convert the filtered varlociraptor output VCF in a way that it contains a GT field?

Bests,
F

**Comment by dlaehnemann** [comment]
Hi @fbemm ,

that's a perfectly valid question and I would also like to have a mechanism to genotype samples with varlociraptor, as there are use cases where you need a genotype. The reason that this does not exist, yet, is that varlociraptor takes the much more nuanced approach of letting you define all kinds of flexible sample setups in the `scenario.yaml` and will output a posterior probability for every event that you specify there -- and these events are defined (mostly) via allele frequency combinations across several samples and thus do not necessarily correspond to genotypes in an individual sample.

So a current solution to getting genotypes for individual samples could be to perform calling on each sample separately with the [scenario suggested in the docs](https://varlociraptor.github.io/docs/calling/) under `Single sample germline calling`, namely:
```
samples:
  hamlet:
    resolution: 5
    universe: "0.0 | 0.5 | 1.0"

events:
  het: "0.5"
  hom: "1.0"
```
With the implicit `absent: "0.0"` event, this covers all three genotypes and you can then for example go and check which event has the maximum posterior probability to decide on a genotype. Or do some filtering first, for example if your are only interested in any event with an alternative allele, you could filter on the `het` and `hom` fields jointly. In any case, you'll currently have to do the parsing for genotyping yourself, which is easiest if you can simply use a tab-separated format downstream. In that case, you could use a new tool from our group, [`vembrane table`](https://github.com/vembrane/vembrane#vembrane-table), which allows for accessing all VCF fields with arbitrary Python syntax:
```
vembrane table --header 'CHROM,POS,GT' 'CHROM, POS, min( [ (INFO["PROB_HET"], "0/1"), (INFO["PROB_HOM"],"1/1"), (INFO["PROB_ABSENT"], "0/0") ], key = lambda x: x[0])[1] ' hamlet.bcf
```
This should get you tab-separated output with `CHROM   POS   GT` fields, so entries like `1       115256379       0/0`.

And if you have a setup with multiple samples where variant calling only really makes sense for a group of samples (e.g. from the same person), you could determine genotypes based on the sample-specific maximum likelihood allele frequency estimate in the `AF` `FORMAT` field. So something like:
```
vembrane table --header 'CHROM,POS,GT' 'CHROM, POS, "./." if FORMAT["AF"]["hamlet"] == "." else "0/0" if FORMAT["AF"]["hamlet"] == 0 else "1/1" if FORMAT["AF"]["hamlet"] == 1 else "0/1" ' hamlet.bcf
```

But I guess that both a default mechanism that allows genotyping based on a sample's allelic frequency estimate and/or a mechanism to specify genotypes in the `scenario.yaml` could be ways to implement genotyping in varlociraptor. Also, @johanneskoester probably has some more sophisticated ideas, already.

**Comment by fbemm** [comment]
Hi @dlaehnemann,

than I was on the right track. Thanks for deep dive, all makes sense! Looking into vembrane right now to convert the VCF output. 

Thx!
F

**Comment by dlaehnemann** [comment]
Also, don't hesitate to post issue over at vembrane. It's still early days, and we're always glad for user feedback, anyway!
