### ISSUE TITLE
Input bcf

### ISSUE THREAD

**Issue by wangjiawen2013** [varlociraptor/varlociraptor#141]
Hi,
Varlociraptor takes bcf generated by other callers (such as Lancet) as input. Lancet generates in output the list of variants in VCF format . All variants (SNVs and indels either shared, specific to the tumor, or specific to the normal) are exported in output.  Do I need to filter the variants first to keep only variants specific to the tumor, or the whole variants is suitable for the input ?

**Comment by wangjiawen2013** [comment]
And, I used the following code to call variants:
varlociraptor call variants tumor-normal --purity 0.75 --tumor tumor.bcf --normal normal.bcf > calls.bcf
The generated calls.bcf was a mixture of vcf and bcf. I cannot view it with bcftools. It showed "Failed to read from strelka_fdr.bcf: unknown file type" When I read it with "cat calls.bcf", some lines are readable characters, and some lines are messy code.

**Comment by dlaehnemann** [comment]
Regarding varlociraptor candidates input from another variant caller: All varlociraptor really cares about, is to know which sites and which possible alleles are to be called. So you could filter some stuff beforehand, or you could simply make varlociraptor call everything and then e.g. use the false discovery rate filtering afterwards to filter to variants that varlociraptor is sure about. Some more info on what these files should look like is in the docs:
https://varlociraptor.github.io/docs/calling/

Regarding the output: This looks like stderr was redirected to stdout somehow. The number of records processed should usually show up on stderr only and not be included when redirecting stdout to a file (`> calls.bcf`). Did you, by any chance, do anything along the lines of the answers to this stackoverflow question:
https://stackoverflow.com/questions/637827/redirect-stderr-and-stdout-in-bash

Also, if you are looking for a good example of a pipeline usage of varlociraptor, you might want to have a look at this snakemake workflow:
https://github.com/snakemake-workflows/dna-seq-varlociraptor

It's still under heavy development, but should include usage of most of the latest varlociraptor features.

**Comment by wangjiawen2013** [comment]
This occured whenI ran "nohup varlociraptor call variants tumor-normal --purity 0.75 --tumor tumor.bcf --normal normal.bcf > calls.bcf & " in background. It warned "nohup: ignoring input and redirecting stderr to stdout".
When I ran "varlociraptor call variants tumor-normal --purity 0.75 --tumor tumor.bcf --normal normal.bcf > calls.bcf". Everything was OK. So how to run it in background ?

**Comment by johanneskoester** [comment]
You can always use tmux or screen for that. In the long run, I strongly suggest to use a workflow management system (e.g. Snakemake). Such data analyses are far to complex to run them manually without loosing track completely.
