### ISSUE TITLE
How to specify tumor purity in the grammar

### ISSUE THREAD

**Issue by nh13** [varlociraptor/varlociraptor#152]
The `varlociraptor call variants tumor-normal` built-in scenario has the `--purity` command line option.  I want to define a custom grammar for tumor-normal calling, how do I specify `purity` for the tumor sample?

**Comment by dlaehnemann** [comment]
You have to specify which sample contaminates which and by which fraction.

Does this part of the docs include all the infos you need?

https://varlociraptor.github.io/docs/calling/#generic-variant-calling

**Comment by nh13** [comment]
Ah yes, I searched for `purity` in the docs which I should have know is just `contamination` `by` the `normal`.

**Comment by dlaehnemann** [comment]
Good point, makes sense to introduce the wording `purity` where `contamination` is explained in the docs, so that its easily findable! See the respective PR in the docs.
