### ISSUE TITLE
Genotype depth does not conform to the VCF spec 

### ISSUE THREAD

**Issue by nh13** [varlociraptor/varlociraptor#160]
The depth (`DP`) in the genotype (format) field is a reserved key in the VCF specification and should be a single value.  If thre are multi-allelic (multiple alternate alleles), then `varlociraptor` will output multiple values in `DP`.  While the header does re-define the `FORMAT/DP` field, it does not conform to spec.

```
##FORMAT=<ID=DP,Number=A,Type=Integer,Description="Expected sequencing depth, while considering mapping uncertainty">
```

This is an issue for parsers like `htsjdk` that optimize the parsing of the reserved INFO and FORMAT keys.

**Comment by johanneskoester** [comment]
Fixed in e92d659956d19f80ee2409dc6f970d272b0dcb76.
