### ISSUE TITLE
Reconcile reported read depths

### ISSUE THREAD

**Issue by nh13** [varlociraptor/varlociraptor#165]
I see in a ver small # of cases where the total sum of read counts is much smaller than what is reported by other tools, for example:
```console
samtools mpileup -r <region> -Q 0 -B -A <in.bam> 
```
or other the `FORMAT/DP` field in various variant callers.   An example would be a depth difference of 500 to 250 I've seen in one variant 

I would have expected that no read filtering is performed and the observation counts would reflect the depth of coverage approximately similar to the `samtools mpileup` command above.  

I've looked at the depth after keeping only properly paired, non-duplicate, QC-pass, high mapping quality reads, and high quality bases.  I still see a depth discrepancy (eg. 350 vs 250 now).

I am sure re-alignment may impact things, but any hint as how to reconcile this further would be appreciated.

**Comment by dlaehnemann** [comment]
The 250 figure made me think of this default value of the `varlociraptor preprocess variants` command:

```
        --max-depth <max-depth>
            Maximum number of observations to use for calling. If locus is exceeding this number, downsampling is
            performed. [default: 200]
```

Could this be it, or did you increase that value? Otherwise, no filtering should be done.

Also, would you consider this default too low and prefer a higher default from your experience?

**Comment by nh13** [comment]
@dlaehnemann that's a totally reasonable limit, perhaps just add a logging statement as I had to search the command line options to find it.  I found it earlier I set the value to 10,000 so that's not it.  Do you see this at all when you compare the `FORMAT/DP` values versus `samtools mpileup`?   

This is a clinical sample so I can't share the test case.  But the observation counts are clearly depressed in this variant using both the depth from samtools pileup as well as the reported depth from three other variant callers. 

The specific example I have shows a tumor depth of:
*  `268` from `varlociraptor`'s `FORMAT/DP` field (this proves that the `--max-depth 10000` option I'm using in `preproce` is being used)
* `461` when I run `samtools mpileup -r <region> -Q 0 -B -A <tumor.bam>`
* `375` when I run `samtools mpileup -r <region> <tumor.bam>`
* `390` when I run ` samtools view -c -q 60 <tumor.bam> <region`
I don't think this is a case of secondary, qc-fail, duplicate reads after examining the SAM flags.

 I also see a general trend across variants variants, see the two figures below.

In the first figure, I see a few variants with siginficantly reduced depth in `varlociraptor` than another variant caller:
* x-axis: the total read depth reported by a different variant caller
* y-axis: the total read depth reported by `varlociraptor` in the `FORMAT/DP` tag

![plots by_depth](https://user-images.githubusercontent.com/846274/118340058-7b9c4180-b4cf-11eb-848a-4f485a04c311.png)

Histogram of the % difference of read depth of `varlociraptor` and the different variant caller (i.e. `100 * abs(Y - X) / X`, where X and Y are defined as the axes in the previous plot).  You can see the left-shifted distribution, so some reads aren't making it through.  
![plots depth_hist](https://user-images.githubusercontent.com/846274/118339426-b0a79480-b4cd-11eb-8b3f-e6f7047be3d2.png)

**Comment by dlaehnemann** [comment]
One thing that will be having an effect here would be the mapping quality. The `DP` is an "expected depth" that factors in the mapping quality:

https://github.com/varlociraptor/varlociraptor/blob/c9a065f98d7995d984b00ef8d3b66896ac3dcba5/src/variants/evidence/observation.rs#L30-L35

However, this does not yet explain the discrepancy with `samtools view -q 60`, which clearly filters for perfectly mapped reads (assuming `bwa` as the mapper;). Here, the filtering of softclipped and non-standard read orientations for SNVs and MNVs might be kicking in:

https://github.com/varlociraptor/varlociraptor/blob/c9a065f98d7995d984b00ef8d3b66896ac3dcba5/src/variants/evidence/observation.rs#L269-L285

Would this explain your current case, and maybe also the others? Are there any SVs or indels in the vicinity, that might lead to softclipped reads? Or any weirdly oriented read pairs?

Or does this filter genuine variants for you that you trust?

**Comment by dlaehnemann** [comment]
Looking at the VCF specs, there's not much of a definition for the `DP` fields (`FORMAT/` and `INFO/`), but I guess the integer does imply that this expects actual read counts. So maybe `EDP` would be a better field name for the current value?

**Comment by nh13** [comment]
I looked at the distribution of the orientation of the pairs, and that looked fine.  But seeing the `. softclipped` filter, I think that's it, since upstream of the reads is a large insertion (~18bp), for which many reads are soft-clipped.  So excluding soft-clipped reads is reducing the coverage for this downstream site, which isn't great.  This goes back to my desire to have phased variants evaluated jointly, but a short-term fix would be to only keep soft-clipped observations if the soft-clipping isn't affecting the variant call.   

I'd assume that for the 18bp insertion, `varlociraptor` will correctly include and re-align those soft-clipped reads if the 18bp insertion is present in the input candidates.  If not, that's probably not a good thing, as that dramatically reduces variant coverage (and thus the accuracy of the allele frequency).  Tools like GATK will happy recover these reads as part of their re-assembly procedure, and since the `varlociraptor` is given the candidates it could do so here.

<img width="737" alt="Screen Shot 2021-05-17 at 12 20 23 PM" src="https://user-images.githubusercontent.com/846274/118544458-4891c200-b70a-11eb-8cb1-66902cb373e3.png">

**Comment by nh13** [comment]
I think this underscores the current limitation of `varlociraptor` that by design it considere the evidence of a single allele at a single site independently.  This is opposite of what the input candidate callers are doing, which is a bit disconcerting:
1. consider jointly the model of two alternate alleles being present (for ploidy 2)
2. consider jointly the evidence of phased variants
3.  accurately report per-allele depth (as well as reference) and frequency

It thus forces the user to:
1. Join phased candidate variant alleles into single large alleles.  For example, the upstream 18b insertion and downstream SNV may be in phase, so we'd need to include an single allele the anchor base, the 18bp insertion, the intermediate reference bases, and the SNV.  We'd need to do the same for the other combinations of alleles (anchor base, no 18bp insertion, intermediate reference, and the SNV).
2. Post-process the output to produce genotypes, and collate depth and allele frequency information.  This gets complicated if you want to decompose the phased variants in the input, since perhaps due to how the reads span the phased alleles, the 18bp insertion has a different depth than the downstream SNV.  Do you report the depths jointly, independently, something else?

Perhaps I'm trying to force a "square peg into a round hole" by wanting to give candidate alleles to `varlociraptor` for it to standardize and call variants (genotypes and allele frequency) to implement consensus/ensemble variant calling (join multiple the alleles observed by multiple input callers).  I do think in my use case consumers of the output will expect genotypes and depth, even for multi-allelic sites and phased variants, the way the current state of the art variant callers produce.

Thus, it may be useful to have a discussion of what could be implemented to support `varlociraptor` in this use case, and how possible plan on how to get there, and if there's opportunity for contributions if there's buy in from the `varlociraptor` authors.

**Comment by johanneskoester** [comment]
I agree with you, handling the softclipped filter differently would be desirable here. One solution is indeed to call jointly. Simply not considering the softclipped reads here as we do now can in corner cases cause problems (e.g. when the SNV is in phase with the indel). Simply considering them can cause problems as well because the softclips can introduce alignment artifacts that can lead to wrong SNV calls.

So, adding support for phased input to varlociraptor would solve the problem I think. As this is already on my list, it will certainly come at some point. But I cannot give you an estimate. Of course, any help would be greatly appreciated. Basically, one would need to use a machinery similar to what we have now for breakends to recognize haplotype blocks and group phased variants together. As for the multi-allelic case, same story here. Already planned, but I cannot yet give you an estimate.

**Comment by nh13** [comment]
As long as your on board, I'm also happy to spend some of my free time helping as much as I can.

**Comment by johanneskoester** [comment]
Certainly!

**Comment by johanneskoester** [comment]
@nh13, I have created a PR with another solution to the problem. Instead of just filtering out softclip reads (which can as outlined above be a bad idea in case of being in phase with an SV) we can recognize softclip induced artifacts via the Varlociraptor bias framework. This should usually yield the full depth, and just trigger a softclip bias if all the reads supporting an SNV also have a softclip. Note that this should not happen if SNV is in phase with an SV, because then there will usually also be reads that do not reach the SV and therefore don't have a soft clip. Of course it can still be possible to construct such a situation. But then it is at least a conservative approach and does not generate a false positive.

**Comment by johanneskoester** [comment]
I think the new bias solves the issue. Closing for now, please feel free to reopen if there are other examples of misleading depth.
