### ISSUE TITLE
Incorrect posterior odds filtering

### ISSUE THREAD

**Issue by bwubb** [varlociraptor/varlociraptor#194]
Hello,
  I am experiencing incorrect posterior odds filtering. Briefly, I executed the following on the same input.
  
`varlociraptor filter-calls posterior-odds --events SOMATIC_TUMOR --odds positive < {input} > {output}`
`varlociraptor filter-calls posterior-odds --events SOMATIC_TUMOR --odds strong < {input} > {output}`

Overall, there are more variants in the 'strong.bcf' output, and many of them probably should not be there. As an example, the following appears in the 'strong.bcf', but not in the 'positive.bcf':

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  normal  tumor
1       204237416       .       C       T       .       .       PROB_ABSENT=353.487;PROB_GERMLINE_HET=4.91533;PROB_GERMLINE_HOM=180.341;PROB_SOMATIC_TUMOR=12.9811;PROB_ARTIFACT=173.191;PROB_SOMATIC_NORMAL=2.02588  DP:AF:OBS:SB:ROB:RPB:SCB:SOBS   7:0.125:1Vp-*^.3Np-<*.2Np->*.1Np+<*.:.:.:.:.:1V6N     17:0.895425:3Vp-<*.2Vp+<*.2Vp-**$2Vp+**$1Vp+>*.1Vp+<^.1Vp->*.2Np-<*.2Np+<*.1Np-*^$:.:.:.:.:12V5N
```

And that is one example of many.

This issue stills feels like user error, but I do not see how. 

Thank you for any help.

*Edit: Maybe I have it backwards and 'positive' is removing too many variants? Are the exact Kass Raftery scores posted somewhere? The ones on wikipedia don't really match. Thank you.

**Comment by johanneskoester** [comment]
Thanks a lot for reporting. I'll try to check it as soon as possible. In the meantime, please note that odds filtering is not really the best approach with Varlociraptor anymore and I will probably deprecate it anyway. There is local FDR control now, which is is much more intuitive (`varlociraptor control-fdr --local`).

**Comment by bwubb** [comment]
Thank you for the reply. This question was asked from several versions of vlr ago; likely deprecated as you say. I will certainly be following the best approach next test. Thank you.
