### ISSUE TITLE
Artifact detection on Oncopanels

### ISSUE THREAD

**Issue by kokyriakidis** [varlociraptor/varlociraptor#283]
Hi!

I would like to ask if I could use Varlociraptor on oncopanels without a prior knowledge on contamination fraction T/N.

More specifically I want to evaluate if a SNV or INDEL **IS NOT** an **ARTIFACT**. I do not want to classify them as GERMLINE OR SOMATIC. 

If it is possible, how is the scenario going to look like for this case?

KK

**Comment by johanneskoester** [comment]
You can assume zero contamination by the normal for such a case. In essence, this means that VAFs will be lower in the tumor (i.e. not corrected for normal cell contamination), but everything else should work fine.
