### ISSUE TITLE
speedup idea likelihood calc: `1-MQ` (cache it and hard-code `1-Prob::from(PHREDProb)`)

### ISSUE THREAD

**Issue by dlaehnemann** [varlociraptor/varlociraptor#37]
Looking at the flamegraph and the respective code again, @aschoen came up with the idea that when we read in PHRED scores with a limited precision, it doesn't make much sense to calculate the complementary likelihood (pseudo-code something like: `1-Prob::from(PHREDProb)`) with higher precision. Instead, we could implement a function / lookup table with something like the following signature:

```
impl PHREDProb {
    /// Lookup of LogProb result for `1 - Prob::from( PHREDProb )`
    pub fn ln_one_minus_int_phred(&self) -> LogProb {
        1 - lookup_tabel_1m_int_phred(self)
    }
}
```

This could be further generalised with arbitrary precision for the PHRED score, but would obviously grow the lookup tabel with every decimal place. Implementation could either go into `libprosic` itself, or into `rust-bio`, if it is of more general interest:
https://github.com/rust-bio/rust-bio/blob/master/src/stats/probs/mod.rs

In addition, we could cache the `LogProb` value of `1 - Mapping Quality` upon reading in the mapping quality of a read, as this is a constant property of an individual read and could be used for multiple candidate sites that a read covers.  The value is used in these two locations:
https://github.com/PROSIC/libprosic/blob/1b6c6a298fa5f95c1ac190e76896d44065762aa9/src/model/likelihood.rs#L66
https://github.com/PROSIC/libprosic/blob/1b6c6a298fa5f95c1ac190e76896d44065762aa9/src/model/likelihood.rs#L93

For this, `Observation` would need an extra field, e.g. something like `one_minus_prob_mapping`:
https://github.com/PROSIC/libprosic/blob/1b6c6a298fa5f95c1ac190e76896d44065762aa9/src/model/evidence/observation.rs#L105-L107

And it should probably be calculated at the same time as `prob_mapping`, so somewhere here:
https://github.com/PROSIC/libprosic/blob/1d82007115e57bb12f5ebd7df6000cb461e27cea/src/model/sample.rs#L425-L448

**Comment by johanneskoester** [comment]
Our performance sprint last year should have solved all these issues.
