### ISSUE TITLE
Calling variants with tumor only vcfs

### ISSUE THREAD

**Issue by grantn5** [varlociraptor/varlociraptor#409]
Hi, thank you very much for developing such a fantastic tool!!!

I am performing variant calling in cancer cell lines and as a result, have no matched normal tissue. Given this algorithm requires normal vcf files to work I was wondering if you think it would be sensible to use a panel of known germline variants in place of the vcf file generated from calling variants in matched normal tissue e.g The known vcfs  hosted on igenomes `Mills_and_1000G_gold_standard.indels.hg38`, `1000G_omni2.5.hg38.vcf`, `1000g_pon.hg38.vcf` and `af-only-gnomad.hg38.vcf`

Thank you in advance for your help!!

**Comment by johanneskoester** [comment]
Hi! Sorry for the delay. It is possible to just have somatic variants as candidates and use a scenario that models the normal sample as a latent one, without given data. Then, the model will just behave as if there are no reads on the normal sample for each candidate variant that you provide for the tumor sample. An example scenario for such a calling is here:
https://varlociraptor.github.io/varlociraptor-scenarios/scenarios/tumor-only-prior/
