### ISSUE TITLE
Varlociraptor Preprocess Variants on CRAM

### ISSUE THREAD

**Issue by FriederikeHanssen** [varlociraptor/varlociraptor#416]
Heya! 

@grant5n and me have been trying to add varlociraptor to nf-core/sarek. A while ago we decided on using CRAM in the pipeline, which seems to cause some issues for us now. 

The issue we run into is:

```
  [E::easy_errno] Libcurl reported error 60 (SSL peer certificate or SSH remote key was not OK)
  [W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/974dc7aec0b755b19f031418fdedf293": Input/output error
  [E::fai_build3_core] Failed to open the file /home/AD/gmackenz/nf-core_test_datasets/test-datasets/data/genomics/homo_sapiens/illumina/cram/../../genome/chr21/sequence/genome.fasta
  [E::refs_load_fai] Failed to open reference file '/home/AD/gmackenz/nf-core_test_datasets/test-datasets/data/genomics/homo_sapiens/illumina/cram/../../genome/chr21/sequence/genome.fasta'
  [E::cram_get_ref] Failed to populate reference for id 0
  [E::cram_decode_slice] Unable to fetch reference #0:13611095-14517308
  ```
  
We updated to version from 8.1.1 to 8.4.5 which fixed this for some options (i.e. `varlociraptor estimate alignment-properties`) but it persists for `  varlociraptor preprocess variants `.

It looks like the problem is that it uses the fasta encoded in the header and not the one we provide via the command line. The full command is:

 ```
 #!/bin/bash -euo pipefail
varlociraptor preprocess variants \
    genome.fasta \
    --alignment-properties sample3.alignment-properties.json \
    --bam test.paired_end.recalibrated.sorted.cram \
    --candidates sample3.strelka.variants.vcf.gz \
     \
    > sample3.vcf.gz
 ```
 
 The respective sarek PR is here: https://github.com/nf-core/sarek/pull/1154 and this can be reproduced with:
 
 ```
nextflow run main.nf \
-profile test_cache,tools_somatic,docker \
--outdir work \
--tools strelka,varlociraptor
 ```
 
  Do we need to specify the fasta differently? Are we doing anything else funky?
 
 Thanks a lot for your help :)

**Comment by johanneskoester** [comment]
I think I have a fix in the referred PR.

**Comment by johanneskoester** [comment]
We indeed forgot to set the reference fasta for the bam/cram reader, so that it would fall back to the reference that is encoded in the header, which might fail as you show above.
