### ISSUE TITLE
how to simulate a cancer genome?

### ISSUE THREAD

**Issue by DayTimeMouse** [varlociraptor/varlociraptor#423]
Hi,

I'm keenly interested in the simulation of cancer genomes.

Could you kindly share me with the code used to simulate the evolutionary genome of cancer clones?

I eagerly await your reply. 

Many thanks, and wishing you all the best.

**Comment by dlaehnemann** [comment]
`varlociraptor` is a tool to call variants in existing next-generation sequencing data. For a full workflow using the tool, you can have a look at:
 https://github.com/snakemake-workflows/dna-seq-varlociraptor

While it can model inheritance among samples, it does not simulate any data. So for generating simulated data, you will have to look elsewhere.
