### ISSUE TITLE
Questions about the tumor-normal variant calling process

### ISSUE THREAD

**Issue by vegetableyu** [varlociraptor/varlociraptor#464]
Hi there,
    I would like to know if it is necessary to run the command 
“varlociraptor preprocess variants reference.fa --alignment-properties sample.alignment-properties.json --bam sample.bam < candidates.bcf > sample.observations.bcf”
    separately on Normal_tissue.bam and Tumor.bam before running “varlociraptor call variants tumor-normal” ?
    Besides, if that is the case, since I only have one output VCF from the Lancet software, should I use it as candidates.bcf for both Normal_tissue and Tumor?
    Thanks in advance!

**Comment by dlaehnemann** [comment]
Yes, the idea of `varlociraptor preprocess` is that you can run this independently on each sample, so this nicely parallelizes the extraction of all the necessary information that is then needed for the joint variant calling on all samples. And yes, you should use the same `candidates.bcf` file for all samples, and these candidates should be generated on some tool run on all of the samples you want to finally call together.

So for `tumor-normal`, you should run Lancet on the tumor and normal sample together, `varlociraptor preprocess` on each sample separately, and `varlociraptor call` on both samples together again.

Hope this helps, let us know if something remains unclear.

**Comment by vegetableyu** [comment]
Thank you for your response! 
I have another question. When I use Manta, I get four files: `candidateSmallIndels.vcf.gz`, `candidateSV.vcf.gz`, `diploidSV.vcf.gz`, and `somaticSV.vcf.gz`. Which one should be used as the "candidates.bcf" ?

**Comment by dlaehnemann** [comment]
I'd say that's for you to decide based on the Manta documentation. Basically, you just give varlociraptor a set of candidate variants that you are interested in, and it determines their probablity based on the data. But what "you are interested in" means for you will be dependent on the particular project.

Also note, that you can also merge multiple vcfs to get a candidate set.

**Comment by vegetableyu** [comment]
Thank you for your response! 
My real confusion is, if I want to study tumor somatic variants, should I retain all variants obtained from upstream SV calling tools in 'candidates.bcf' (including somatic variants, germline variants, and shared variants), or only the somatic variants?
I assume it should be all variants? Since 'candidates.bcf' is also needed when running the 'varlociraptor preprocess' command to process Normal_tissue.bam.

**Comment by dlaehnemann** [comment]
If you are certain, that the classification into those classes is correct, and you are only interested in somatic stuff, and you want to minimize the work that varlociraptor has to do, you can just take the somatic candidates, I'd say. Otherwise, you can let varlociraptor decide what group they actually belong to. In any case, you might be interested in having a look at generic variant calling and setting up a dedicated `scenario.yaml` file for your project:
https://varlociraptor.github.io/docs/calling/#generic-variant-calling
