### ISSUE TITLE
WGBS usability: Some VAFs differ significantly from the OBS string

### ISSUE THREAD

**Issue by jafors** [varlociraptor/varlociraptor#76]
In WGBS samples, there seems to be an accumulation of differences in the VAF  compared to a manual calculation from the observations vector. This might be due to lower quality in BQ and MAPQ(?)
Testcase is attached.

[testcase_511950.zip](https://github.com/varlociraptor/varlociraptor/files/3460047/testcase_511950.zip)

**Comment by johanneskoester** [comment]
Solved by personal discussion.
