### ISSUE TITLE
candidates.bcf format

### ISSUE THREAD

**Issue by brucemoran** [varlociraptor/varlociraptor#87]
Hi,

I know you have test files for candidates.bcf, but do you have an example of the minimum requirements for this file? I am merging from ensemble somatic calling so reducing the required input would be useful.

Thanks,

Bruce.

**Comment by johanneskoester** [comment]
All it needs is CHROM, POS, REF, ALT. The rest is ignored. But good point, we will update the docs accordingly.

**Comment by johanneskoester** [comment]
Or for large deletions, it can additionally use SVLEN if ALT is `<DEL>`.

**Comment by brucemoran** [comment]
Great, that is really good news!

**Comment by johanneskoester** [comment]
Fixed in the docs. Thank you!
