### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by cmeesters** [varlociraptor/varlociraptor#91]
Hi,

I'm trying to support Varlociraptor for easybuild. 
Just successfully wrote the easyconfig file and managed to install on our cluster. Tomorrow will be the big day, where this is polished and contributed to the easybuild trunk - hopefully. 

However, my first attempt failed with:

<snip>

 cgu.8:function rgsl::randist::gaussian::ugaussian_P::h1653d8d3fa81c115: error: undefined reference to 'gsl_cdf_ugaussian_P'
          collect2: error: ld returned 1 exit status

I figured, this must be in GSL. Hence, an otherwise not mentioned dependency is GSL. Could you guys / Johannes perhaps add a build instruction file to the next release? Even though Varlociraptor is support via Bioconda, not every community enclined to resort to *conda.

Best regards,
Christian Meesters

**Comment by johanneskoester** [comment]
Good catch. That was not intentional. I have updated the docs here: https://varlociraptor.github.io/docs/installation/

**Comment by johanneskoester** [comment]
Please reopen if there are futher installation issues.
