### ISSUE TITLE
Found argument '--odds' which wasn't expected

### ISSUE THREAD

**Issue by brucemoran** [varlociraptor/varlociraptor#97]
Running 
`varlociraptor filter-calls posterior-odds --events SOMATIC_TUMOR --odds strong < calls.bcf` 
results in 
`error: Found argument '--odds' which wasn't expected, or isn't valid in this context`

control-fdr works as expected

varlociraptor 1.5.0
CentOs7, Singularity [here](https://cloud.sylabs.io/library/_container/5d24ff503a2c26622b038314)(somatic_exome_n-of-1)

**Comment by johanneskoester** [comment]
Thanks for reporting! Fixed with commit 96fe3ac.
